/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Gayatri Mantra",
    "artist": "Anuradha Paudwal",
    "year": null,
    "q": "Gayatri Mantra Anuradha Paudwal",
    "yt": null
  },
  {
    "title": "Vishnu Sahasranamam",
    "artist": "M. S. Subbulakshmi",
    "year": null,
    "q": "Vishnu Sahasranamam M. S. Subbulakshmi",
    "yt": null
  },
  {
    "title": "Om Namah Shivaya Dhun",
    "artist": "Traditional",
    "year": null,
    "q": "Om Namah Shivaya Dhun Traditional",
    "yt": null
  },
  {
    "title": "Achyutam Keshavam",
    "artist": "Traditional",
    "year": null,
    "q": "Achyutam Keshavam Traditional",
    "yt": null
  },
  {
    "title": "Madhurashtakam",
    "artist": "Traditional (Vallabhacharya)",
    "year": null,
    "q": "Madhurashtakam Traditional (Vallabhacharya)",
    "yt": null
  },
  {
    "title": "Hare Krishna Hare Rama Dhun",
    "artist": "Traditional",
    "year": null,
    "q": "Hare Krishna Hare Rama Dhun Traditional",
    "yt": null
  },
  {
    "title": "Santan Gopal Mantra",
    "artist": "Traditional",
    "year": null,
    "q": "Santan Gopal Mantra Traditional",
    "yt": null
  },
  {
    "title": "Ganesh Atharvashirsha",
    "artist": "Traditional",
    "year": null,
    "q": "Ganesh Atharvashirsha Traditional",
    "yt": null
  },
  {
    "title": "Shri Ram Chandra Kripalu",
    "artist": "Traditional (Tulsidas)",
    "year": null,
    "q": "Shri Ram Chandra Kripalu Traditional (Tulsidas)",
    "yt": null
  },
  {
    "title": "Bhagyada Lakshmi Baramma",
    "artist": "M. S. Subbulakshmi",
    "year": null,
    "q": "Bhagyada Lakshmi Baramma M. S. Subbulakshmi",
    "yt": null
  },
  {
    "title": "Om Jai Jagdish Hare",
    "artist": "Traditional",
    "year": null,
    "q": "Om Jai Jagdish Hare Traditional",
    "yt": null
  },
  {
    "title": "Raghupati Raghav Raja Ram",
    "artist": "Traditional",
    "year": null,
    "q": "Raghupati Raghav Raja Ram Traditional",
    "yt": null
  },
  {
    "title": "Payoji Maine Ram Ratan Dhan Payo",
    "artist": "Lata Mangeshkar",
    "year": null,
    "q": "Payoji Maine Ram Ratan Dhan Payo Lata Mangeshkar",
    "yt": null
  },
  {
    "title": "Itni Shakti Hamein Dena Data",
    "artist": "Sushma Shreshtha, Pushpa Pagdhare",
    "year": 1983,
    "q": "Itni Shakti Hamein Dena Data Sushma Shreshtha, Pushpa Pagdhare",
    "yt": null
  },
  {
    "title": "Ae Malik Tere Bande Hum",
    "artist": "Vani Jairam",
    "year": 1957,
    "q": "Ae Malik Tere Bande Hum Vani Jairam",
    "yt": null
  },
  {
    "title": "Tu Pyar Ka Sagar Hai",
    "artist": "Manna Dey",
    "year": 1959,
    "q": "Tu Pyar Ka Sagar Hai Manna Dey",
    "yt": null
  },
  {
    "title": "Sri Suktam",
    "artist": "Traditional",
    "year": null,
    "q": "Sri Suktam Traditional",
    "yt": null
  },
  {
    "title": "Vakratunda Mahakaya",
    "artist": "Traditional",
    "year": null,
    "q": "Vakratunda Mahakaya Traditional",
    "yt": null
  }
];

window.SITE = {
  "name": "Garbh Sanskar",
  "tagline": "Bhajans for the nine months of waiting.",
  "glyph": "✿",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": null,
  "maxSeconds": 3600
};
