/* ============================================================
   build.mjs — generates sites/<slug>/ for every theme, plus the
   hub page at the repo root.

   Run:  node build.mjs
   ============================================================ */

import { mkdirSync, writeFileSync, existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { themes, GRAIN } from "./themes/themes.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SITES = join(ROOT, "sites");

/** Public origin, used only for absolute og:/twitter: URLs. Set this to the
 *  real domain before launch — link previews need absolute URLs. */
const ORIGIN = process.env.SITE_ORIGIN || "https://music-eight-smoky.vercel.app";

/* ---------- helpers ------------------------------------------------- */

const esc = (s) =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

/** Merge previously-resolved YouTube ids back in so `node build.mjs`
 *  never wipes work done by scripts/fill-ids.mjs. */
function existingIds(slug) {
  const file = join(SITES, slug, "playlist.js");
  if (!existsSync(file)) return {};
  const map = {};
  const src = readFileSync(file, "utf8");
  const re = /"title":\s*"((?:[^"\\]|\\.)*)"[\s\S]*?"yt":\s*(?:"([\w-]{11})"|null)/g;
  let m;
  while ((m = re.exec(src))) {
    if (m[2]) map[JSON.parse('"' + m[1] + '"')] = m[2];
  }
  return map;
}

/* ---------- per-site files ------------------------------------------ */

function trackList(theme) {
  const known = existingIds(theme.slug);
  return theme.tracks.map(([title, artist, year]) => ({
    title,
    artist,
    year: year ?? null,
    q: `${title} ${artist}`,
    yt: known[title] ?? null
  }));
}

function siteConfig(theme) {
  return {
    name: theme.name,
    tagline: theme.tagline,
    glyph: theme.glyph,
    shuffle: true,
    searchFallback: true,
    ytPlaylist: theme.ytPlaylist || null,
    maxSeconds: theme.maxSeconds || null
  };
}

function playlistFile(theme) {
  return `/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = ${JSON.stringify(trackList(theme), null, 2)};

window.SITE = ${JSON.stringify(siteConfig(theme), null, 2)};
`;
}

function themeCss(theme) {
  const vars = Object.entries(theme.tokens)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join("\n");

  return `/* generated by build.mjs — edit themes/themes.mjs instead */
:root {
${vars}
  --font-display: "${theme.fonts.display}", Georgia, serif;
  --font-body: "${theme.fonts.body}", system-ui, -apple-system, sans-serif;
  --grain-url: ${GRAIN};
}
${(theme.css || "").replace(/^\n/, "")}
`;
}

function indexHtml(theme) {
  const url = `${ORIGIN}/sites/${theme.slug}/`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${esc(theme.name)} — ${esc(theme.tagline)}</title>
<meta name="description" content="${esc(theme.ogDesc)}">
<meta name="theme-color" content="${theme.tokens["--bg"]}">

<meta property="og:type" content="website">
<meta property="og:url" content="${url}">
<meta property="og:title" content="${esc(theme.name)}">
<meta property="og:description" content="${esc(theme.ogDesc)}">
<meta property="og:image" content="${url}og.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(theme.name)}">
<meta name="twitter:description" content="${esc(theme.ogDesc)}">
<meta name="twitter:image" content="${url}og.png">

<link rel="icon" href="favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="favicon.svg">
<link rel="mask-icon" href="favicon.svg" color="${theme.tokens["--accent"]}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="${theme.fonts.href}" id="theme-fonts">
<link rel="stylesheet" href="../../shared/base.css">
<link rel="stylesheet" href="theme.css" id="theme-css">
</head>
<body>

<div class="scene">${theme.scene.trim()}</div>

<main class="stage">
  <header class="masthead">
    <h1 class="sign">${esc(theme.sign).replace(/ {2}/g, "&nbsp;&nbsp;")}<small>${esc(theme.kicker)}</small></h1>
    <nav class="masthead-links">
      <a href="../../index.html">all stations</a>
    </nav>
  </header>

  <section class="center">
    <div class="card">
      <div class="art" id="art"></div>

      <div class="track">
        <h2 class="track-title" id="track-title">—</h2>
        <p class="track-meta" id="track-meta"></p>
      </div>

      <div class="ticker"><span id="ticker-text"></span></div>

      <div class="transport">
        <button class="tbtn" id="btn-prev" aria-label="Previous">
          <svg viewBox="0 0 24 24"><path d="M6 6h2v12H6zm3 6l9 6V6z"/></svg>
        </button>
        <button class="tbtn tbtn--main" id="btn-play" aria-label="Play">
          <svg viewBox="0 0 24 24"><path id="icon-play" d="M8 5v14l11-7z"/></svg>
        </button>
        <button class="tbtn" id="btn-next" aria-label="Next">
          <svg viewBox="0 0 24 24"><path d="M16 6h2v12h-2zM6 18l9-6-9-6z"/></svg>
        </button>
      </div>

      <div class="volume">
        <svg viewBox="0 0 24 24"><path d="M3 9v6h4l5 5V4L7 9zm13.5 3a4.5 4.5 0 0 0-2.5-4v8a4.5 4.5 0 0 0 2.5-4z"/></svg>
        <input type="range" id="volume" min="0" max="100" value="65" aria-label="Volume">
      </div>

      <p class="status" id="status"></p>
    </div>
  </section>

  <footer class="footer">
    <span id="count"></span>
    <span id="counter" class="counter"></span>
    <span>${esc(theme.tagline)}</span>
  </footer>
</main>

<div class="gate" id="gate">
  <div class="gate-inner">
    <h2>${esc(theme.gateTitle)}</h2>
    <p>${esc(theme.gateCopy)}</p>
    <button class="gate-btn" id="gate-btn">
      <svg viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>
      play
    </button>
  </div>
</div>

<div id="yt-host"></div>

<script src="../../shared/stations.js"></script>
<script src="playlist.js"></script>
<script src="../../shared/player.js"></script>
<script src="../../shared/counter.js" defer></script>
${theme.js ? `<script>${theme.js.trim()}</script>` : ""}
</body>
</html>
`;
}

/* OG share card. SVG is generated here; convert to og.png before launch
   (see README) because X/WhatsApp will not render an SVG link preview. */
function ogSvg(theme) {
  const bg = theme.tokens["--bg"];
  const accent = theme.tokens["--accent"];
  const dim = theme.tokens["--ink-dim"];
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <defs>
    <radialGradient id="g" cx="50%" cy="0%" r="90%">
      <stop offset="0%" stop-color="${accent}" stop-opacity="0.28"/>
      <stop offset="100%" stop-color="${bg}" stop-opacity="0"/>
    </radialGradient>
    <filter id="n"><feTurbulence type="fractalNoise" baseFrequency="0.85" numOctaves="3"/></filter>
  </defs>
  <rect width="1200" height="630" fill="${bg}"/>
  <rect width="1200" height="630" fill="url(#g)"/>
  <text x="600" y="290" text-anchor="middle" font-family="${theme.fonts.display}, Georgia, serif"
        font-size="96" fill="${accent}">${esc(theme.sign)}</text>
  <text x="600" y="356" text-anchor="middle" font-family="${theme.fonts.body}, sans-serif"
        font-size="27" letter-spacing="7" fill="${dim}">${esc(
          theme.kicker.toUpperCase()
        )}</text>
  <text x="600" y="452" text-anchor="middle" font-family="${theme.fonts.body}, sans-serif"
        font-size="34" fill="#ffffff" opacity="0.9">${esc(theme.tagline)}</text>
  <text x="600" y="566" text-anchor="middle" font-family="${theme.fonts.body}, sans-serif"
        font-size="24" letter-spacing="10" fill="${accent}" opacity="0.8">${esc(theme.name.toUpperCase())}</text>
  <rect width="1200" height="630" filter="url(#n)" opacity="0.06"/>
</svg>
`;
}

/* Favicon: accent-filled tile with the station glyph, so ten open tabs stay
   tellable apart at 16px. The glyph is rendered as text — every one used is
   in the system emoji/symbol fallback chain on macOS, Windows and Android. */
function faviconSvg({ bg, fg, glyph, size = 0.62 }) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="14" fill="${bg}"/>
  <text x="32" y="32" text-anchor="middle" dominant-baseline="central"
        font-size="${Math.round(64 * size)}" fill="${fg}"
        font-family="Helvetica Neue, Segoe UI Symbol, Noto Sans Symbols 2, sans-serif"
      >${esc(glyph)}&#xFE0E;</text>
</svg>
`;
}

/* ---------- hub ------------------------------------------------------ */

function hubHtml() {
  const card = (t) => `      <a class="station" href="sites/${t.slug}/index.html"
         style="--a:${t.tokens["--accent"]};--b:${t.tokens["--bg"]}">
        <span class="glyph">${t.glyph}</span>
        <strong>${esc(t.name)}</strong>
        <em>${esc(t.kicker)}</em>
        <p>${esc(t.tagline)}</p>
        <small>${t.tracks.length} tracks · ${t.kind}</small>
      </a>`;

  const group = (kind, title, note) => `    <h2 class="group">${title}<small>${note}</small></h2>
    <div class="grid">
${themes.filter((t) => t.kind === kind).map(card).join("\n")}
    </div>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Stations — nostalgia radio</title>
<meta name="description" content="Ten single-page nostalgia radio stations. One place or genre each, one song at a time.">
<meta name="theme-color" content="#0b0b0d">
<link rel="icon" href="favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="favicon.svg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Anton&family=Inter:wght@400;600&display=swap">
<style>
  *,*::before,*::after{box-sizing:border-box}
  body{margin:0;background:#0b0b0d;color:#f2efe9;font-family:Inter,system-ui,sans-serif;
    padding:clamp(24px,6vw,72px);line-height:1.5}
  h1{font-family:Anton,sans-serif;font-size:clamp(34px,8vw,68px);margin:0;letter-spacing:.02em}
  .lede{color:#8f8a82;max-width:56ch;margin:14px 0 52px}
  .group{font-family:Anton,sans-serif;font-weight:400;font-size:15px;letter-spacing:.28em;
    text-transform:uppercase;color:#8f8a82;margin:52px 0 18px;display:flex;gap:14px;align-items:baseline}
  .group small{font-family:Inter,sans-serif;letter-spacing:0;text-transform:none;font-size:12px;opacity:.7}
  .grid{display:grid;gap:14px;grid-template-columns:repeat(auto-fill,minmax(258px,1fr))}
  .station{position:relative;display:block;text-decoration:none;color:inherit;padding:22px;
    border:1px solid #ffffff14;border-radius:10px;overflow:hidden;
    background:linear-gradient(160deg,color-mix(in srgb,var(--a) 12%,transparent),var(--b));
    transition:transform .16s ease,border-color .16s ease}
  .station:hover{transform:translateY(-3px);border-color:color-mix(in srgb,var(--a) 55%,transparent)}
  .glyph{position:absolute;right:16px;top:10px;font-size:44px;color:var(--a);opacity:.28}
  .station strong{display:block;font-family:Anton,sans-serif;font-weight:400;font-size:23px;
    letter-spacing:.02em;color:var(--a)}
  .station em{display:block;font-style:normal;font-size:11px;letter-spacing:.2em;
    text-transform:uppercase;color:#ffffff5c;margin:5px 0 12px}
  .station p{margin:0 0 14px;font-size:14px;color:#d8d3ca;min-height:42px}
  .station small{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#ffffff45}
  footer{margin-top:64px;font-size:12px;color:#6d6862;max-width:64ch;line-height:1.7}
  .counter{display:block;margin-top:10px;color:#8f8a82;letter-spacing:.1em;
    text-transform:uppercase;font-size:11px}
  .counter:empty{display:none}
  .counter-dot{display:inline-block;width:6px;height:6px;border-radius:50%;
    background:#5bd08a;margin-right:8px;vertical-align:middle;
    animation:pulse 2s ease-out infinite}
  .counter-sep{margin:0 8px;opacity:.5}
  @keyframes pulse{0%{box-shadow:0 0 0 0 rgba(91,208,138,.6)}
    70%{box-shadow:0 0 0 7px transparent}100%{box-shadow:0 0 0 0 transparent}}
  @media (max-width:760px){
    body{padding:22px 16px calc(28px + env(safe-area-inset-bottom))}
    h1{font-size:clamp(30px,10vw,44px)}
    .lede{margin:10px 0 30px;font-size:14px}
    .group{margin:30px 0 12px;font-size:12px;letter-spacing:.2em;
      flex-direction:column;gap:2px;align-items:flex-start}
    .grid{grid-template-columns:1fr;gap:8px}
    .station{padding:16px;min-height:74px}
    .station p{display:none}
    .station em{margin:4px 0 0}
    .glyph{font-size:32px;top:14px}
    footer{margin-top:38px;font-size:11px}
  }
  footer code{background:#ffffff10;padding:2px 6px;border-radius:4px}
</style>
</head>
<body>
  <h1>Nostalgia radio</h1>
  <p class="lede">Ten single-page stations. Each one is a place or a genre, one song at a time,
     no accounts, no search. Pick a station and leave it playing.</p>

${group("place", "Places", "a specific room, at a specific time")}

${group("genre", "Genres", "the sound itself, in its own era")}

  <footer>
    Audio streams through the official YouTube IFrame API — nothing is hosted here.
    <span id="counter" class="counter"></span>
  </footer>
  <script src="shared/counter.js" defer></script>
</body>
</html>
`;
}

/* ---------- run ------------------------------------------------------- */

let written = 0;
for (const theme of themes) {
  const dir = join(SITES, theme.slug);
  const playlist = playlistFile(theme); // read old ids BEFORE wiping
  const idCount = (playlist.match(/"yt": "/g) || []).length;

  // Overwrite the generated files in place rather than wiping the directory —
  // og.png and any other hand-made asset alongside them must survive a rebuild.
  mkdirSync(dir, { recursive: true });

  writeFileSync(join(dir, "index.html"), indexHtml(theme));
  writeFileSync(join(dir, "theme.css"), themeCss(theme));
  writeFileSync(join(dir, "playlist.js"), playlist);
  writeFileSync(join(dir, "og.svg"), ogSvg(theme));
  writeFileSync(
    join(dir, "favicon.svg"),
    faviconSvg({
      bg: theme.tokens["--accent"],
      fg: theme.tokens["--on-accent"] || theme.tokens["--bg"],
      glyph: theme.glyph
    })
  );

  written++;
  console.log(
    `  ${theme.slug.padEnd(16)} ${String(theme.tracks.length).padStart(2)} tracks` +
      `  ${idCount}/${theme.tracks.length} ids resolved`
  );
}

/* Every station in one file, so the switcher can change stations in place
   instead of navigating — a page load would tear down the audio. */
writeFileSync(
  join(ROOT, "shared", "stations.js"),
  "window.STATIONS = " +
    JSON.stringify(
      themes.map((t) => ({
        slug: t.slug,
        kind: t.kind,
        name: t.name,
        signHtml: esc(t.sign).replace(/ {2}/g, "&nbsp;&nbsp;"),
        kicker: t.kicker,
        tagline: t.tagline,
        glyph: t.glyph,
        accent: t.tokens["--accent"],
        bg: t.tokens["--bg"],
        fontsHref: t.fonts.href,
        scene: t.scene.trim(),
        site: siteConfig(t),
        tracks: trackList(t)
      })),
      null,
      1
    ) +
    ";\n"
);

writeFileSync(join(ROOT, "index.html"), hubHtml());
writeFileSync(
  join(ROOT, "favicon.svg"),
  faviconSvg({ bg: "#0b0b0d", fg: "#f2efe9", glyph: "◉", size: 0.5 })
);
console.log(`\nbuilt ${written} stations + hub → open index.html`);
