/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Ae Mere Humsafar",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1988,
    "q": "Ae Mere Humsafar Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Papa Kehte Hain",
    "artist": "Udit Narayan",
    "year": 1988,
    "q": "Papa Kehte Hain Udit Narayan",
    "yt": null
  },
  {
    "title": "Tumse Milne Ki Tamanna",
    "artist": "S. P. Balasubrahmanyam",
    "year": 1991,
    "q": "Tumse Milne Ki Tamanna S. P. Balasubrahmanyam",
    "yt": null
  },
  {
    "title": "Bahut Pyar Karte Hain",
    "artist": "Anuradha Paudwal",
    "year": 1991,
    "q": "Bahut Pyar Karte Hain Anuradha Paudwal",
    "yt": null
  },
  {
    "title": "Jaadu Teri Nazar",
    "artist": "Udit Narayan",
    "year": 1993,
    "q": "Jaadu Teri Nazar Udit Narayan",
    "yt": null
  },
  {
    "title": "Tu Mere Samne",
    "artist": "Lata Mangeshkar, Udit Narayan",
    "year": 1993,
    "q": "Tu Mere Samne Lata Mangeshkar, Udit Narayan",
    "yt": null
  },
  {
    "title": "Baazigar O Baazigar",
    "artist": "Kumar Sanu, Alka Yagnik",
    "year": 1993,
    "q": "Baazigar O Baazigar Kumar Sanu, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Yeh Kaali Kaali Aankhen",
    "artist": "Kumar Sanu, Anu Malik",
    "year": 1993,
    "q": "Yeh Kaali Kaali Aankhen Kumar Sanu, Anu Malik",
    "yt": null
  },
  {
    "title": "Chura Ke Dil Mera",
    "artist": "Kumar Sanu, Alka Yagnik",
    "year": 1994,
    "q": "Chura Ke Dil Mera Kumar Sanu, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Aisi Deewangi",
    "artist": "Kumar Sanu, Vinod Rathod",
    "year": 1992,
    "q": "Aisi Deewangi Kumar Sanu, Vinod Rathod",
    "yt": null
  },
  {
    "title": "Sochenge Tumhe Pyar",
    "artist": "Kumar Sanu",
    "year": 1992,
    "q": "Sochenge Tumhe Pyar Kumar Sanu",
    "yt": null
  },
  {
    "title": "Dil Hai Ke Manta Nahin",
    "artist": "Kumar Sanu, Anuradha Paudwal",
    "year": 1991,
    "q": "Dil Hai Ke Manta Nahin Kumar Sanu, Anuradha Paudwal",
    "yt": null
  },
  {
    "title": "Pehla Nasha",
    "artist": "Udit Narayan, Sadhana Sargam",
    "year": 1992,
    "q": "Pehla Nasha Udit Narayan, Sadhana Sargam",
    "yt": null
  },
  {
    "title": "Tujhe Dekha To",
    "artist": "Kumar Sanu, Lata Mangeshkar",
    "year": 1995,
    "q": "Tujhe Dekha To Kumar Sanu, Lata Mangeshkar",
    "yt": null
  },
  {
    "title": "Rangeela Re",
    "artist": "Asha Bhosle",
    "year": 1995,
    "q": "Rangeela Re Asha Bhosle",
    "yt": null
  },
  {
    "title": "Pardesi Pardesi",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1996,
    "q": "Pardesi Pardesi Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Kuch Kuch Hota Hai",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1998,
    "q": "Kuch Kuch Hota Hai Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Akele Hain To Kya Gham Hai",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1988,
    "q": "Akele Hain To Kya Gham Hai Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Meri Mehbooba",
    "artist": "Kumar Sanu, Alka Yagnik",
    "year": 1997,
    "q": "Meri Mehbooba Kumar Sanu, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Kuch Na Kaho",
    "artist": "Kumar Sanu",
    "year": 1994,
    "q": "Kuch Na Kaho Kumar Sanu",
    "yt": null
  }
];

window.SITE = {
  "name": "Cassette",
  "tagline": "One cassette, both sides, played until the tape stretched.",
  "glyph": "▤",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLinVjP-aRmlukMwFfIb5u0xA-M_Be3nC5"
};
