/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Ab Tere Bin Ji Lenge Hum",
    "artist": "Kumar Sanu",
    "year": 1990,
    "q": "Ab Tere Bin Ji Lenge Hum Kumar Sanu",
    "yt": "rXHY4Cv9cA8"
  },
  {
    "title": "Dheere Dheere Se Meri Zindagi",
    "artist": "Kumar Sanu, Anuradha Paudwal",
    "year": 1990,
    "q": "Dheere Dheere Se Meri Zindagi Kumar Sanu, Anuradha Paudwal",
    "yt": "KeyfUuXPOcY"
  },
  {
    "title": "Bas Ek Sanam Chahiye",
    "artist": "Kumar Sanu",
    "year": 1990,
    "q": "Bas Ek Sanam Chahiye Kumar Sanu",
    "yt": "fBylcT-TWZw"
  },
  {
    "title": "Saanson Ki Zaroorat Hai Jaise",
    "artist": "Kumar Sanu",
    "year": 1990,
    "q": "Saanson Ki Zaroorat Hai Jaise Kumar Sanu",
    "yt": "YCuhzjK11iA"
  },
  {
    "title": "Mera Dil Bhi Kitna Pagal Hai",
    "artist": "Kumar Sanu, Alka Yagnik",
    "year": 1991,
    "q": "Mera Dil Bhi Kitna Pagal Hai Kumar Sanu, Alka Yagnik",
    "yt": "DIvHIjOYq3U"
  },
  {
    "title": "Dil Hai Ke Manta Nahin",
    "artist": "Kumar Sanu, Anuradha Paudwal",
    "year": 1991,
    "q": "Dil Hai Ke Manta Nahin Kumar Sanu, Anuradha Paudwal",
    "yt": "U0qBRoeQa-g"
  },
  {
    "title": "Sochenge Tumhe Pyar",
    "artist": "Kumar Sanu",
    "year": 1992,
    "q": "Sochenge Tumhe Pyar Kumar Sanu",
    "yt": "lFdSi01tpYM"
  },
  {
    "title": "Aisi Deewangi",
    "artist": "Kumar Sanu, Vinod Rathod",
    "year": 1992,
    "q": "Aisi Deewangi Kumar Sanu, Vinod Rathod",
    "yt": "EvVE4qdxkmU"
  },
  {
    "title": "Wada Raha Sanam",
    "artist": "Kumar Sanu",
    "year": 1992,
    "q": "Wada Raha Sanam Kumar Sanu",
    "yt": "9b0iydtDZLU"
  },
  {
    "title": "Baazigar O Baazigar",
    "artist": "Kumar Sanu, Alka Yagnik",
    "year": 1993,
    "q": "Baazigar O Baazigar Kumar Sanu, Alka Yagnik",
    "yt": "dPElPtPAz7Y"
  },
  {
    "title": "Yeh Kaali Kaali Aankhein",
    "artist": "Kumar Sanu",
    "year": 1993,
    "q": "Yeh Kaali Kaali Aankhein Kumar Sanu",
    "yt": "KC-DuX51NY0"
  },
  {
    "title": "Kitabein Bahut Si",
    "artist": "Kumar Sanu, Asha Bhosle",
    "year": 1993,
    "q": "Kitabein Bahut Si Kumar Sanu, Asha Bhosle",
    "yt": "ieu6xnwJxdA"
  },
  {
    "title": "Chura Ke Dil Mera",
    "artist": "Kumar Sanu, Alka Yagnik",
    "year": 1994,
    "q": "Chura Ke Dil Mera Kumar Sanu, Alka Yagnik",
    "yt": "Yqj1_V90KJo"
  },
  {
    "title": "Ek Ladki Ko Dekha",
    "artist": "Kumar Sanu",
    "year": 1994,
    "q": "Ek Ladki Ko Dekha Kumar Sanu",
    "yt": "htMvfOfixuM"
  },
  {
    "title": "Kuch Na Kaho",
    "artist": "Kumar Sanu",
    "year": 1994,
    "q": "Kuch Na Kaho Kumar Sanu",
    "yt": "Kidtrrn4aUM"
  },
  {
    "title": "Bahon Ke Darmiyan",
    "artist": "Kumar Sanu, Kavita Krishnamurthy",
    "year": 1996,
    "q": "Bahon Ke Darmiyan Kumar Sanu, Kavita Krishnamurthy",
    "yt": "kHYYfKAQdHA"
  },
  {
    "title": "Do Dil Mil Rahe Hain",
    "artist": "Kumar Sanu",
    "year": 1997,
    "q": "Do Dil Mil Rahe Hain Kumar Sanu",
    "yt": "eKIpHujNdX0"
  },
  {
    "title": "Meri Mehbooba",
    "artist": "Kumar Sanu, Alka Yagnik",
    "year": 1997,
    "q": "Meri Mehbooba Kumar Sanu, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Ek Din Aap Yun Humko Mil Jayenge",
    "artist": "Kumar Sanu, Alka Yagnik",
    "year": 1997,
    "q": "Ek Din Aap Yun Humko Mil Jayenge Kumar Sanu, Alka Yagnik",
    "yt": "90Q5bMN6u2w"
  },
  {
    "title": "Tumhe Jo Maine Dekha",
    "artist": "Kumar Sanu",
    "year": 2004,
    "q": "Tumhe Jo Maine Dekha Kumar Sanu",
    "yt": "84TjXsRHf6Q"
  }
];

window.SITE = {
  "name": "Kumar Sanu",
  "tagline": "Side A of a tape bought in 1990, still holding its pitch.",
  "glyph": "♪",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLinVjP-aRmluiFicvkJtzUsm18L556cpK",
  "maxSeconds": null
};
