/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Ole Ole",
    "artist": "Vinod Rathod",
    "year": 1994,
    "q": "Ole Ole Vinod Rathod",
    "yt": null
  },
  {
    "title": "Tu Cheez Badi Hai Mast",
    "artist": "Udit Narayan, Kavita Krishnamurthy",
    "year": 1994,
    "q": "Tu Cheez Badi Hai Mast Udit Narayan, Kavita Krishnamurthy",
    "yt": null
  },
  {
    "title": "Didi Tera Devar Deewana",
    "artist": "Lata Mangeshkar, S. P. Balasubrahmanyam",
    "year": 1994,
    "q": "Didi Tera Devar Deewana Lata Mangeshkar, S. P. Balasubrahmanyam",
    "yt": null
  },
  {
    "title": "Sona Kitna Sona Hai",
    "artist": "Poornima, Vinod Rathod",
    "year": 1997,
    "q": "Sona Kitna Sona Hai Poornima, Vinod Rathod",
    "yt": null
  },
  {
    "title": "Aati Kya Khandala",
    "artist": "Aamir Khan, Alka Yagnik",
    "year": 1998,
    "q": "Aati Kya Khandala Aamir Khan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Chaiyya Chaiyya",
    "artist": "Sukhwinder Singh, Sapna Awasthi",
    "year": 1998,
    "q": "Chaiyya Chaiyya Sukhwinder Singh, Sapna Awasthi",
    "yt": null
  },
  {
    "title": "Muqabla",
    "artist": "Mano, Swarnalatha",
    "year": 1994,
    "q": "Muqabla Mano, Swarnalatha",
    "yt": null
  },
  {
    "title": "Urvashi Urvashi",
    "artist": "A. R. Rahman, Suresh Peters",
    "year": 1994,
    "q": "Urvashi Urvashi A. R. Rahman, Suresh Peters",
    "yt": null
  },
  {
    "title": "Rangeela Re",
    "artist": "Asha Bhosle",
    "year": 1995,
    "q": "Rangeela Re Asha Bhosle",
    "yt": null
  },
  {
    "title": "Ek Do Teen",
    "artist": "Alka Yagnik",
    "year": 1988,
    "q": "Ek Do Teen Alka Yagnik",
    "yt": null
  },
  {
    "title": "Dhak Dhak Karne Laga",
    "artist": "Anuradha Paudwal, Udit Narayan",
    "year": 1992,
    "q": "Dhak Dhak Karne Laga Anuradha Paudwal, Udit Narayan",
    "yt": null
  },
  {
    "title": "Jhanjhariya",
    "artist": "Kumar Sanu, Alka Yagnik",
    "year": 1996,
    "q": "Jhanjhariya Kumar Sanu, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Oonchi Hai Building",
    "artist": "Poornima, Abhijeet",
    "year": 1997,
    "q": "Oonchi Hai Building Poornima, Abhijeet",
    "yt": null
  },
  {
    "title": "Chunari Chunari",
    "artist": "Abhijeet, Anuradha Sriram",
    "year": 1999,
    "q": "Chunari Chunari Abhijeet, Anuradha Sriram",
    "yt": null
  },
  {
    "title": "Tunak Tunak Tun",
    "artist": "Daler Mehndi",
    "year": 1998,
    "q": "Tunak Tunak Tun Daler Mehndi",
    "yt": null
  },
  {
    "title": "Bolo Ta Ra Ra",
    "artist": "Daler Mehndi",
    "year": 1995,
    "q": "Bolo Ta Ra Ra Daler Mehndi",
    "yt": null
  },
  {
    "title": "Main Nikla Gaddi Leke",
    "artist": "Udit Narayan",
    "year": 2001,
    "q": "Main Nikla Gaddi Leke Udit Narayan",
    "yt": null
  },
  {
    "title": "Kaho Naa Pyaar Hai",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 2000,
    "q": "Kaho Naa Pyaar Hai Udit Narayan, Alka Yagnik",
    "yt": null
  }
];

window.SITE = {
  "name": "Meter Down",
  "tagline": "FM Rainbow hits at 4x volume through one blown speaker.",
  "glyph": "◍",
  "shuffle": true,
  "searchFallback": true
};
