/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Dam Mast Qalandar",
    "artist": "Nusrat Fateh Ali Khan",
    "year": null,
    "q": "Dam Mast Qalandar Nusrat Fateh Ali Khan",
    "yt": "94QB7xfOkqM"
  },
  {
    "title": "Allah Hoo",
    "artist": "Nusrat Fateh Ali Khan",
    "year": null,
    "q": "Allah Hoo Nusrat Fateh Ali Khan",
    "yt": "lCDMR7TEFew"
  },
  {
    "title": "Tumhe Dillagi",
    "artist": "Nusrat Fateh Ali Khan",
    "year": null,
    "q": "Tumhe Dillagi Nusrat Fateh Ali Khan",
    "yt": null
  },
  {
    "title": "Afreen Afreen",
    "artist": "Nusrat Fateh Ali Khan",
    "year": 1996,
    "q": "Afreen Afreen Nusrat Fateh Ali Khan",
    "yt": null
  },
  {
    "title": "Sanson Ki Mala",
    "artist": "Nusrat Fateh Ali Khan",
    "year": null,
    "q": "Sanson Ki Mala Nusrat Fateh Ali Khan",
    "yt": null
  },
  {
    "title": "Mera Piya Ghar Aaya",
    "artist": "Nusrat Fateh Ali Khan",
    "year": null,
    "q": "Mera Piya Ghar Aaya Nusrat Fateh Ali Khan",
    "yt": "ctOgc7cgay0"
  },
  {
    "title": "Yeh Jo Halka Halka Suroor",
    "artist": "Nusrat Fateh Ali Khan",
    "year": null,
    "q": "Yeh Jo Halka Halka Suroor Nusrat Fateh Ali Khan",
    "yt": null
  },
  {
    "title": "Kinna Sohna",
    "artist": "Nusrat Fateh Ali Khan",
    "year": null,
    "q": "Kinna Sohna Nusrat Fateh Ali Khan",
    "yt": null
  },
  {
    "title": "Tajdar-e-Haram",
    "artist": "Sabri Brothers",
    "year": null,
    "q": "Tajdar-e-Haram Sabri Brothers",
    "yt": "nB-epINHDHA"
  },
  {
    "title": "Bhar Do Jholi Meri",
    "artist": "Sabri Brothers",
    "year": null,
    "q": "Bhar Do Jholi Meri Sabri Brothers",
    "yt": null
  },
  {
    "title": "Chaap Tilak",
    "artist": "Abida Parveen",
    "year": null,
    "q": "Chaap Tilak Abida Parveen",
    "yt": "f3dnF-GmscM"
  },
  {
    "title": "Tere Ishq Nachaya",
    "artist": "Abida Parveen",
    "year": null,
    "q": "Tere Ishq Nachaya Abida Parveen",
    "yt": null
  },
  {
    "title": "Damadam Mast Qalandar",
    "artist": "Abida Parveen",
    "year": null,
    "q": "Damadam Mast Qalandar Abida Parveen",
    "yt": null
  },
  {
    "title": "Aaj Rang Hai",
    "artist": "Traditional (Amir Khusrau)",
    "year": null,
    "q": "Aaj Rang Hai Traditional (Amir Khusrau)",
    "yt": null
  },
  {
    "title": "Khwaja Mere Khwaja",
    "artist": "A. R. Rahman",
    "year": 2008,
    "q": "Khwaja Mere Khwaja A. R. Rahman",
    "yt": null
  },
  {
    "title": "Kun Faya Kun",
    "artist": "A. R. Rahman, Javed Ali, Mohit Chauhan",
    "year": 2011,
    "q": "Kun Faya Kun A. R. Rahman, Javed Ali, Mohit Chauhan",
    "yt": null
  },
  {
    "title": "Arziyan",
    "artist": "Javed Ali, Kailash Kher",
    "year": 2009,
    "q": "Arziyan Javed Ali, Kailash Kher",
    "yt": null
  },
  {
    "title": "Piya Haji Ali",
    "artist": "A. R. Rahman, Srinivas",
    "year": 2000,
    "q": "Piya Haji Ali A. R. Rahman, Srinivas",
    "yt": null
  }
];

window.SITE = {
  "name": "Dargah",
  "tagline": "Thursday night at the dargah, hands clapping on the offbeat.",
  "glyph": "❋",
  "shuffle": true,
  "searchFallback": true
};
