/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Pehla Nasha",
    "artist": "Udit Narayan, Sadhana Sargam",
    "year": 1992,
    "q": "Pehla Nasha Udit Narayan, Sadhana Sargam",
    "yt": "SBfPs-PMGTA"
  },
  {
    "title": "Ole Ole",
    "artist": "Vinod Rathod",
    "year": 1994,
    "q": "Ole Ole Vinod Rathod",
    "yt": "hcCvSmjHwGY"
  },
  {
    "title": "Koi Mil Gaya",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1998,
    "q": "Koi Mil Gaya Udit Narayan, Alka Yagnik",
    "yt": "Foh01tG09Nk"
  },
  {
    "title": "Aati Kya Khandala",
    "artist": "Aamir Khan, Alka Yagnik",
    "year": 1998,
    "q": "Aati Kya Khandala Aamir Khan, Alka Yagnik",
    "yt": "EENnVk1_suc"
  },
  {
    "title": "Kaho Naa Pyaar Hai",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 2000,
    "q": "Kaho Naa Pyaar Hai Udit Narayan, Alka Yagnik",
    "yt": "-LESbtPT8uw"
  },
  {
    "title": "Bole Chudiyan",
    "artist": "Sonu Nigam, Alka Yagnik",
    "year": 2001,
    "q": "Bole Chudiyan Sonu Nigam, Alka Yagnik",
    "yt": "IBvg3WeqP1U"
  },
  {
    "title": "It's The Time To Disco",
    "artist": "Shaan, Vasundhara Das",
    "year": 2003,
    "q": "It's The Time To Disco Shaan, Vasundhara Das",
    "yt": null
  },
  {
    "title": "Dhoom Machale",
    "artist": "Sunidhi Chauhan",
    "year": 2004,
    "q": "Dhoom Machale Sunidhi Chauhan",
    "yt": "2uUmHTgT65I"
  },
  {
    "title": "Kajra Re",
    "artist": "Alisha Chinai, Shankar Mahadevan",
    "year": 2005,
    "q": "Kajra Re Alisha Chinai, Shankar Mahadevan",
    "yt": "4dsFQFCvVGU"
  },
  {
    "title": "Where's The Party Tonight",
    "artist": "Shaan, Vasundhara Das",
    "year": 2006,
    "q": "Where's The Party Tonight Shaan, Vasundhara Das",
    "yt": "ifT-NS_E7EY"
  },
  {
    "title": "Desi Girl",
    "artist": "Vishal Dadlani, Sunidhi Chauhan",
    "year": 2008,
    "q": "Desi Girl Vishal Dadlani, Sunidhi Chauhan",
    "yt": "wDIrpvH8MzE"
  },
  {
    "title": "Twist",
    "artist": "Neeraj Shridhar",
    "year": 2008,
    "q": "Twist Neeraj Shridhar",
    "yt": "KgmeL_xuB0I"
  },
  {
    "title": "Ainvayi Ainvayi",
    "artist": "Salim Merchant, Sunidhi Chauhan",
    "year": 2010,
    "q": "Ainvayi Ainvayi Salim Merchant, Sunidhi Chauhan",
    "yt": "pElk1ShPrcE"
  },
  {
    "title": "Senorita",
    "artist": "Farhan Akhtar, Hrithik Roshan, Abhay Deol",
    "year": 2011,
    "q": "Senorita Farhan Akhtar, Hrithik Roshan, Abhay Deol",
    "yt": "2Z0Put0teCM"
  },
  {
    "title": "Ilahi",
    "artist": "Arijit Singh",
    "year": 2013,
    "q": "Ilahi Arijit Singh",
    "yt": "fdubeMFwuGs"
  },
  {
    "title": "Balam Pichkari",
    "artist": "Vishal Dadlani, Shalmali Kholgade",
    "year": 2013,
    "q": "Balam Pichkari Vishal Dadlani, Shalmali Kholgade",
    "yt": "0WtRNGubWGA"
  },
  {
    "title": "Badtameez Dil",
    "artist": "Benny Dayal",
    "year": 2013,
    "q": "Badtameez Dil Benny Dayal",
    "yt": "II2EO3Nw4m0"
  },
  {
    "title": "Gallan Goodiyaan",
    "artist": "Various Artists",
    "year": 2015,
    "q": "Gallan Goodiyaan Various Artists",
    "yt": "jCEdTq3j-0U"
  },
  {
    "title": "Sooraj Dooba Hain",
    "artist": "Arijit Singh, Aditi Singh Sharma",
    "year": 2015,
    "q": "Sooraj Dooba Hain Arijit Singh, Aditi Singh Sharma",
    "yt": "nJZcbidTutE"
  },
  {
    "title": "Kar Gayi Chull",
    "artist": "Badshah, Fazilpuria, Neha Kakkar",
    "year": 2016,
    "q": "Kar Gayi Chull Badshah, Fazilpuria, Neha Kakkar",
    "yt": "NTHz9ephYTw"
  }
];

window.SITE = {
  "name": "Khushi",
  "tagline": "The ones everybody still knows every word of.",
  "glyph": "☀",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLGpLqaMxppFrVsjOt_yA45AaF9j1u6cbC",
  "maxSeconds": null
};
