/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Feather",
    "artist": "Nujabes",
    "year": null,
    "q": "Feather Nujabes",
    "yt": "4yX8ZUgraOo"
  },
  {
    "title": "Aruarian Dance",
    "artist": "Nujabes",
    "year": null,
    "q": "Aruarian Dance Nujabes",
    "yt": "qYcoJpqCha4"
  },
  {
    "title": "Luv (sic) Pt. 3",
    "artist": "Nujabes",
    "year": null,
    "q": "Luv (sic) Pt. 3 Nujabes",
    "yt": "JC2q7kRqhig"
  },
  {
    "title": "Counting Stars",
    "artist": "Nujabes",
    "year": null,
    "q": "Counting Stars Nujabes",
    "yt": "Z-tTmSY4m4M"
  },
  {
    "title": "Snowman",
    "artist": "WYS",
    "year": null,
    "q": "Snowman WYS",
    "yt": null
  },
  {
    "title": "Affection",
    "artist": "Jinsang",
    "year": null,
    "q": "Affection Jinsang",
    "yt": "6jGPypPNEg4"
  },
  {
    "title": "Summer's Day",
    "artist": "Jinsang",
    "year": null,
    "q": "Summer's Day Jinsang",
    "yt": "vNZA0RQ54p4"
  },
  {
    "title": "Controlla",
    "artist": "Idealism",
    "year": null,
    "q": "Controlla Idealism",
    "yt": "LkhPi6J5Xg0"
  },
  {
    "title": "Both of Us",
    "artist": "Idealism",
    "year": null,
    "q": "Both of Us Idealism",
    "yt": "Djz-AXDO27Q"
  },
  {
    "title": "Harbor",
    "artist": "Tomppabeats",
    "year": null,
    "q": "Harbor Tomppabeats",
    "yt": null
  },
  {
    "title": "Owls of the Night",
    "artist": "Kupla",
    "year": null,
    "q": "Owls of the Night Kupla",
    "yt": "bmxt4B_5_K8"
  },
  {
    "title": "Staying There",
    "artist": "L'indécis",
    "year": null,
    "q": "Staying There L'indécis",
    "yt": "buqsSywAlmA"
  },
  {
    "title": "Soulful",
    "artist": "L'indécis",
    "year": null,
    "q": "Soulful L'indécis",
    "yt": "7ZguAEoNpZw"
  },
  {
    "title": "just friends",
    "artist": "potsu",
    "year": null,
    "q": "just friends potsu",
    "yt": "qOif_ni_9zc"
  },
  {
    "title": "Seasons",
    "artist": "Aso",
    "year": null,
    "q": "Seasons Aso",
    "yt": "Xo3ez6LThQ4"
  },
  {
    "title": "Pathway",
    "artist": "eevee",
    "year": null,
    "q": "Pathway eevee",
    "yt": "YWN2aaE6OP0"
  },
  {
    "title": "Lucid",
    "artist": "Philanthrope",
    "year": null,
    "q": "Lucid Philanthrope",
    "yt": "FhylZiUAJwo"
  },
  {
    "title": "Under Water",
    "artist": "Sleepy Fish",
    "year": null,
    "q": "Under Water Sleepy Fish",
    "yt": null
  }
];

window.SITE = {
  "name": "Monsoon",
  "tagline": "Rain on the window, a tape loop, and homework you never finished.",
  "glyph": "❍",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PL6fhs6TSspZv0F0YgsG-p7Mn189CU2XKS",
  "maxSeconds": null
};
