/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Ranjish Hi Sahi",
    "artist": "Mehdi Hassan",
    "year": null,
    "q": "Ranjish Hi Sahi Mehdi Hassan",
    "yt": "dOtqwZdhBkc"
  },
  {
    "title": "Rafta Rafta Woh Meri",
    "artist": "Mehdi Hassan",
    "year": null,
    "q": "Rafta Rafta Woh Meri Mehdi Hassan",
    "yt": "Y01l7QTtIoE"
  },
  {
    "title": "Mujhe Tum Nazar Se",
    "artist": "Mehdi Hassan",
    "year": null,
    "q": "Mujhe Tum Nazar Se Mehdi Hassan",
    "yt": "6sMEV_Hvv-g"
  },
  {
    "title": "Ab Ke Hum Bichhde",
    "artist": "Mehdi Hassan",
    "year": null,
    "q": "Ab Ke Hum Bichhde Mehdi Hassan",
    "yt": null
  },
  {
    "title": "Chupke Chupke Raat Din",
    "artist": "Ghulam Ali",
    "year": null,
    "q": "Chupke Chupke Raat Din Ghulam Ali",
    "yt": "MWjaK_nW72E"
  },
  {
    "title": "Hungama Hai Kyon Barpa",
    "artist": "Ghulam Ali",
    "year": null,
    "q": "Hungama Hai Kyon Barpa Ghulam Ali",
    "yt": "xQsMn1kmJs4"
  },
  {
    "title": "Aawargi",
    "artist": "Ghulam Ali",
    "year": null,
    "q": "Aawargi Ghulam Ali",
    "yt": "pZWqn3BC17Q"
  },
  {
    "title": "Tum Itna Jo Muskura Rahe Ho",
    "artist": "Jagjit Singh",
    "year": 1982,
    "q": "Tum Itna Jo Muskura Rahe Ho Jagjit Singh",
    "yt": "In3yneec2hk"
  },
  {
    "title": "Ahista Ahista",
    "artist": "Jagjit Singh",
    "year": null,
    "q": "Ahista Ahista Jagjit Singh",
    "yt": "vukyvBndFR8"
  },
  {
    "title": "Woh Kagaz Ki Kashti",
    "artist": "Jagjit Singh",
    "year": null,
    "q": "Woh Kagaz Ki Kashti Jagjit Singh",
    "yt": "tB0hmrY_s0U"
  },
  {
    "title": "Baat Niklegi To Phir",
    "artist": "Jagjit Singh",
    "year": null,
    "q": "Baat Niklegi To Phir Jagjit Singh",
    "yt": "LUIeuo2PJPA"
  },
  {
    "title": "Tere Aane Ki Jab Khabar Mehke",
    "artist": "Jagjit Singh",
    "year": null,
    "q": "Tere Aane Ki Jab Khabar Mehke Jagjit Singh",
    "yt": "-G_Xi_x4g1s"
  },
  {
    "title": "Hoshwalon Ko Khabar Kya",
    "artist": "Jagjit Singh",
    "year": 1999,
    "q": "Hoshwalon Ko Khabar Kya Jagjit Singh",
    "yt": "hZuwe72Rtcc"
  },
  {
    "title": "Chithi Na Koi Sandesh",
    "artist": "Jagjit Singh",
    "year": 1998,
    "q": "Chithi Na Koi Sandesh Jagjit Singh",
    "yt": "sBBzwoSngGg"
  },
  {
    "title": "Aaj Jaane Ki Zid Na Karo",
    "artist": "Farida Khanum",
    "year": null,
    "q": "Aaj Jaane Ki Zid Na Karo Farida Khanum",
    "yt": "CfUDuYAasjE"
  },
  {
    "title": "Dil Cheez Kya Hai",
    "artist": "Asha Bhosle",
    "year": 1981,
    "q": "Dil Cheez Kya Hai Asha Bhosle",
    "yt": "eFcs3p1moMA"
  },
  {
    "title": "In Aankhon Ki Masti",
    "artist": "Asha Bhosle",
    "year": 1981,
    "q": "In Aankhon Ki Masti Asha Bhosle",
    "yt": "yjYE41bYnUM"
  },
  {
    "title": "Chandi Jaisa Rang",
    "artist": "Pankaj Udhas",
    "year": null,
    "q": "Chandi Jaisa Rang Pankaj Udhas",
    "yt": "G4NAKKy5k0g"
  },
  {
    "title": "Kabhi Kisi Ko Muqammal",
    "artist": "Bhupinder Singh",
    "year": 1982,
    "q": "Kabhi Kisi Ko Muqammal Bhupinder Singh",
    "yt": null
  },
  {
    "title": "Yeh Dhuan Sa Kahan Se Uthta Hai",
    "artist": "Jagjit Singh",
    "year": null,
    "q": "Yeh Dhuan Sa Kahan Se Uthta Hai Jagjit Singh",
    "yt": "thOylhHN-Bc"
  }
];

window.SITE = {
  "name": "Mehfil",
  "tagline": "Wine-dark room, one harmonium, and a couplet that ruins you.",
  "glyph": "۞",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLJeNQvgQ4Sl-WJX41V39pPd3oQxKNc7EA",
  "maxSeconds": 1800
};
