/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Garbh Raksha Stotram",
    "artist": "Traditional",
    "year": null,
    "q": "Garbh Raksha Stotram Traditional",
    "yt": null
  },
  {
    "title": "Santan Gopal Mantra",
    "artist": "Traditional",
    "year": null,
    "q": "Santan Gopal Mantra Traditional",
    "yt": null
  },
  {
    "title": "Om Namo Bhagavate Vasudevaya",
    "artist": "Traditional",
    "year": null,
    "q": "Om Namo Bhagavate Vasudevaya Traditional",
    "yt": null
  },
  {
    "title": "Devaki Suta Govinda",
    "artist": "Traditional",
    "year": null,
    "q": "Devaki Suta Govinda Traditional",
    "yt": null
  },
  {
    "title": "Gayatri Mantra",
    "artist": "Anuradha Paudwal",
    "year": null,
    "q": "Gayatri Mantra Anuradha Paudwal",
    "yt": null
  },
  {
    "title": "Mahamrityunjaya Mantra",
    "artist": "Traditional",
    "year": null,
    "q": "Mahamrityunjaya Mantra Traditional",
    "yt": null
  },
  {
    "title": "Vishnu Sahasranamam",
    "artist": "M. S. Subbulakshmi",
    "year": null,
    "q": "Vishnu Sahasranamam M. S. Subbulakshmi",
    "yt": null
  },
  {
    "title": "Ganapati Atharvashirsha",
    "artist": "Traditional",
    "year": null,
    "q": "Ganapati Atharvashirsha Traditional",
    "yt": null
  },
  {
    "title": "Ram Raksha Stotra",
    "artist": "Traditional",
    "year": null,
    "q": "Ram Raksha Stotra Traditional",
    "yt": null
  },
  {
    "title": "Bhagavad Gita Adhyay 15 - Purushottama Yoga",
    "artist": "Traditional",
    "year": null,
    "q": "Bhagavad Gita Adhyay 15 - Purushottama Yoga Traditional",
    "yt": null
  },
  {
    "title": "Madhurashtakam",
    "artist": "Traditional (Vallabhacharya)",
    "year": null,
    "q": "Madhurashtakam Traditional (Vallabhacharya)",
    "yt": null
  },
  {
    "title": "Achyutam Keshavam",
    "artist": "Traditional",
    "year": null,
    "q": "Achyutam Keshavam Traditional",
    "yt": null
  },
  {
    "title": "Ya Kundendu Tushara Hara - Saraswati Vandana",
    "artist": "Traditional",
    "year": null,
    "q": "Ya Kundendu Tushara Hara - Saraswati Vandana Traditional",
    "yt": null
  },
  {
    "title": "Shri Suktam",
    "artist": "Traditional",
    "year": null,
    "q": "Shri Suktam Traditional",
    "yt": null
  },
  {
    "title": "Purusha Suktam",
    "artist": "Traditional",
    "year": null,
    "q": "Purusha Suktam Traditional",
    "yt": null
  },
  {
    "title": "Yashomati Maiya Se",
    "artist": "Lata Mangeshkar, Manna Dey",
    "year": 1972,
    "q": "Yashomati Maiya Se Lata Mangeshkar, Manna Dey",
    "yt": null
  },
  {
    "title": "Chanda Hai Tu Mera Suraj Hai Tu",
    "artist": "Lata Mangeshkar",
    "year": 1969,
    "q": "Chanda Hai Tu Mera Suraj Hai Tu Lata Mangeshkar",
    "yt": null
  },
  {
    "title": "Om Chanting 108 Times",
    "artist": "Traditional",
    "year": null,
    "q": "Om Chanting 108 Times Traditional",
    "yt": null
  }
];

window.SITE = {
  "name": "Bhajan",
  "tagline": "The mantras played for the baby, all nine months.",
  "glyph": "✿",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": null,
  "maxSeconds": 3600
};
