/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Hanuman Chalisa",
    "artist": "Hariharan",
    "year": null,
    "q": "Hanuman Chalisa Hariharan",
    "yt": "AETFvQonfV8"
  },
  {
    "title": "Shiv Tandav Stotram",
    "artist": "Traditional",
    "year": null,
    "q": "Shiv Tandav Stotram Traditional",
    "yt": "hMBKmQEPNzI"
  },
  {
    "title": "Om Jai Jagdish Hare",
    "artist": "Traditional",
    "year": null,
    "q": "Om Jai Jagdish Hare Traditional",
    "yt": "NE3SWh9_vR4"
  },
  {
    "title": "Sukhkarta Dukhharta",
    "artist": "Traditional",
    "year": null,
    "q": "Sukhkarta Dukhharta Traditional",
    "yt": null
  },
  {
    "title": "Jai Ambe Gauri",
    "artist": "Traditional",
    "year": null,
    "q": "Jai Ambe Gauri Traditional",
    "yt": null
  },
  {
    "title": "Om Jai Shiv Omkara",
    "artist": "Traditional",
    "year": null,
    "q": "Om Jai Shiv Omkara Traditional",
    "yt": null
  },
  {
    "title": "Aarti Kunj Bihari Ki",
    "artist": "Traditional",
    "year": null,
    "q": "Aarti Kunj Bihari Ki Traditional",
    "yt": "FEMR5alT7CY"
  },
  {
    "title": "Achyutam Keshavam",
    "artist": "Traditional",
    "year": null,
    "q": "Achyutam Keshavam Traditional",
    "yt": "3yczGKnskts"
  },
  {
    "title": "Shri Ram Chandra Kripalu",
    "artist": "Traditional (Tulsidas)",
    "year": null,
    "q": "Shri Ram Chandra Kripalu Traditional (Tulsidas)",
    "yt": "fkSmiW9D50w"
  },
  {
    "title": "Raghupati Raghav Raja Ram",
    "artist": "Traditional",
    "year": null,
    "q": "Raghupati Raghav Raja Ram Traditional",
    "yt": null
  },
  {
    "title": "Gayatri Mantra",
    "artist": "Anuradha Paudwal",
    "year": null,
    "q": "Gayatri Mantra Anuradha Paudwal",
    "yt": null
  },
  {
    "title": "Mahamrityunjaya Mantra",
    "artist": "Traditional",
    "year": null,
    "q": "Mahamrityunjaya Mantra Traditional",
    "yt": null
  },
  {
    "title": "Vishnu Sahasranamam",
    "artist": "M. S. Subbulakshmi",
    "year": null,
    "q": "Vishnu Sahasranamam M. S. Subbulakshmi",
    "yt": null
  },
  {
    "title": "Ganapati Atharvashirsha",
    "artist": "Traditional",
    "year": null,
    "q": "Ganapati Atharvashirsha Traditional",
    "yt": null
  },
  {
    "title": "Madhurashtakam",
    "artist": "Traditional (Vallabhacharya)",
    "year": null,
    "q": "Madhurashtakam Traditional (Vallabhacharya)",
    "yt": "XE1ANx0go6E"
  },
  {
    "title": "Payoji Maine Ram Ratan Dhan Payo",
    "artist": "Lata Mangeshkar",
    "year": null,
    "q": "Payoji Maine Ram Ratan Dhan Payo Lata Mangeshkar",
    "yt": "GsItAp8ZPk4"
  },
  {
    "title": "Man Tarpat Hari Darshan Ko Aaj",
    "artist": "Mohammed Rafi",
    "year": 1952,
    "q": "Man Tarpat Hari Darshan Ko Aaj Mohammed Rafi",
    "yt": "AczxIEZNb_o"
  },
  {
    "title": "Itni Shakti Hamein Dena Data",
    "artist": "Sushma Shreshtha, Pushpa Pagdhare",
    "year": 1983,
    "q": "Itni Shakti Hamein Dena Data Sushma Shreshtha, Pushpa Pagdhare",
    "yt": "m1Ft4JdgrBE"
  },
  {
    "title": "Ae Malik Tere Bande Hum",
    "artist": "Vani Jairam",
    "year": 1957,
    "q": "Ae Malik Tere Bande Hum Vani Jairam",
    "yt": null
  },
  {
    "title": "Tu Pyar Ka Sagar Hai",
    "artist": "Manna Dey",
    "year": 1959,
    "q": "Tu Pyar Ka Sagar Hai Manna Dey",
    "yt": null
  }
];

window.SITE = {
  "name": "Bhajan",
  "tagline": "Evening aarti, the Chalisa, and whatever plays after.",
  "glyph": "✿",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLQCEIlUXozCw",
  "maxSeconds": 3600
};
