/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Sandese Aate Hain",
    "artist": "Sonu Nigam, Roop Kumar Rathod",
    "year": 1997,
    "q": "Sandese Aate Hain Sonu Nigam, Roop Kumar Rathod",
    "yt": "yccGxvIydKg"
  },
  {
    "title": "Yeh Dil Deewana",
    "artist": "Sonu Nigam",
    "year": 1997,
    "q": "Yeh Dil Deewana Sonu Nigam",
    "yt": "_4Ft9UIKzwk"
  },
  {
    "title": "Deewana Tera",
    "artist": "Sonu Nigam",
    "year": 1999,
    "q": "Deewana Tera Sonu Nigam",
    "yt": "J8zlroVMYeM"
  },
  {
    "title": "Satrangi Re",
    "artist": "Sonu Nigam, Kavita Krishnamurthy",
    "year": 1998,
    "q": "Satrangi Re Sonu Nigam, Kavita Krishnamurthy",
    "yt": "OClXVLsI4jM"
  },
  {
    "title": "Suraj Hua Maddham",
    "artist": "Sonu Nigam, Alka Yagnik",
    "year": 2001,
    "q": "Suraj Hua Maddham Sonu Nigam, Alka Yagnik",
    "yt": "iqNS2Qe4pp0"
  },
  {
    "title": "Tanhayee",
    "artist": "Sonu Nigam",
    "year": 2001,
    "q": "Tanhayee Sonu Nigam",
    "yt": "ikZp7S19-eo"
  },
  {
    "title": "Saathiya",
    "artist": "Sonu Nigam",
    "year": 2002,
    "q": "Saathiya Sonu Nigam",
    "yt": "6vMEtXqLh1A"
  },
  {
    "title": "Kal Ho Naa Ho",
    "artist": "Sonu Nigam",
    "year": 2003,
    "q": "Kal Ho Naa Ho Sonu Nigam",
    "yt": "g0eO74UmRBs"
  },
  {
    "title": "Har Ghadi Badal Rahi Hai",
    "artist": "Sonu Nigam",
    "year": 2003,
    "q": "Har Ghadi Badal Rahi Hai Sonu Nigam",
    "yt": "g0eO74UmRBs"
  },
  {
    "title": "Maahi Ve",
    "artist": "Sonu Nigam, Sadhana Sargam",
    "year": 2003,
    "q": "Maahi Ve Sonu Nigam, Sadhana Sargam",
    "yt": "1BWdglekty0"
  },
  {
    "title": "Main Hoon Na",
    "artist": "Sonu Nigam",
    "year": 2004,
    "q": "Main Hoon Na Sonu Nigam",
    "yt": "Op_UWVBWj3c"
  },
  {
    "title": "Do Pal",
    "artist": "Sonu Nigam, Lata Mangeshkar",
    "year": 2004,
    "q": "Do Pal Sonu Nigam, Lata Mangeshkar",
    "yt": "HPsxxBhv9kc"
  },
  {
    "title": "Sau Dard",
    "artist": "Sonu Nigam",
    "year": 2006,
    "q": "Sau Dard Sonu Nigam",
    "yt": "6tFtRnkhSe4"
  },
  {
    "title": "Kabhi Alvida Naa Kehna",
    "artist": "Sonu Nigam",
    "year": 2006,
    "q": "Kabhi Alvida Naa Kehna Sonu Nigam",
    "yt": "nmTp_esz_Q8"
  },
  {
    "title": "In Lamhon Ke Daaman Mein",
    "artist": "Sonu Nigam, Madhushree",
    "year": 2008,
    "q": "In Lamhon Ke Daaman Mein Sonu Nigam, Madhushree",
    "yt": "iJtVLgLFtOw"
  },
  {
    "title": "Guzarish",
    "artist": "Sonu Nigam, Javed Ali",
    "year": 2008,
    "q": "Guzarish Sonu Nigam, Javed Ali",
    "yt": "ztPa6vkM-yY"
  },
  {
    "title": "Abhi Mujh Mein Kahin",
    "artist": "Sonu Nigam",
    "year": 2012,
    "q": "Abhi Mujh Mein Kahin Sonu Nigam",
    "yt": "oWKgpB2zpgw"
  },
  {
    "title": "Suno Na Sangemarmar",
    "artist": "Sonu Nigam",
    "year": 2014,
    "q": "Suno Na Sangemarmar Sonu Nigam",
    "yt": "83pr5QLz6Bc"
  }
];

window.SITE = {
  "name": "Sonu Nigam",
  "tagline": "The voice you played on the rooftop while the whole colony slept.",
  "glyph": "☾",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLoN8qntcwH4itUYa8LT1H8YKGLhLYdtWd",
  "maxSeconds": null
};
