/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Tunak Tunak Tun",
    "artist": "Daler Mehndi",
    "year": 1998,
    "q": "Tunak Tunak Tun Daler Mehndi",
    "yt": "92ydUdqWE1g"
  },
  {
    "title": "Bolo Ta Ra Ra",
    "artist": "Daler Mehndi",
    "year": 1995,
    "q": "Bolo Ta Ra Ra Daler Mehndi",
    "yt": "h6Ze5Hqa1wA"
  },
  {
    "title": "Mundian To Bach Ke",
    "artist": "Panjabi MC",
    "year": 1998,
    "q": "Mundian To Bach Ke Panjabi MC",
    "yt": "x9WO2ieJMYk"
  },
  {
    "title": "Gur Nalo Ishq Mitha",
    "artist": "Malkit Singh",
    "year": 1998,
    "q": "Gur Nalo Ishq Mitha Malkit Singh",
    "yt": "_rGz16v3CUM"
  },
  {
    "title": "Jugni",
    "artist": "Arif Lohar, Meesha Shafi",
    "year": 2010,
    "q": "Jugni Arif Lohar, Meesha Shafi",
    "yt": "gjaH2iuoYWE"
  },
  {
    "title": "Ki Banu Duniya Da",
    "artist": "Gurdas Maan",
    "year": 1987,
    "q": "Ki Banu Duniya Da Gurdas Maan",
    "yt": "pjQyBF2gwjQ"
  },
  {
    "title": "3 Peg",
    "artist": "Sharry Mann",
    "year": 2016,
    "q": "3 Peg Sharry Mann",
    "yt": "hzTg4zPBtDU"
  },
  {
    "title": "Suit Suit",
    "artist": "Guru Randhawa",
    "year": 2017,
    "q": "Suit Suit Guru Randhawa",
    "yt": "uQ763VvqiEM"
  },
  {
    "title": "High Rated Gabru",
    "artist": "Guru Randhawa",
    "year": 2017,
    "q": "High Rated Gabru Guru Randhawa",
    "yt": "hjWf8A0YNSE"
  },
  {
    "title": "Lahore",
    "artist": "Guru Randhawa",
    "year": 2018,
    "q": "Lahore Guru Randhawa",
    "yt": "dZ0fwJojhrs"
  },
  {
    "title": "Laembadgini",
    "artist": "Diljit Dosanjh",
    "year": 2016,
    "q": "Laembadgini Diljit Dosanjh",
    "yt": "15Sjjl_24x0"
  },
  {
    "title": "5 Taara",
    "artist": "Diljit Dosanjh",
    "year": 2017,
    "q": "5 Taara Diljit Dosanjh",
    "yt": "MsTW5cyWKj4"
  },
  {
    "title": "Proper Patola",
    "artist": "Diljit Dosanjh",
    "year": 2013,
    "q": "Proper Patola Diljit Dosanjh",
    "yt": "GVhmynWOPoM"
  },
  {
    "title": "Wakhra Swag",
    "artist": "Navraj Hans",
    "year": 2015,
    "q": "Wakhra Swag Navraj Hans",
    "yt": null
  },
  {
    "title": "Brown Munde",
    "artist": "AP Dhillon",
    "year": 2020,
    "q": "Brown Munde AP Dhillon",
    "yt": "VNs_cCtdbPc"
  },
  {
    "title": "Excuses",
    "artist": "AP Dhillon",
    "year": 2020,
    "q": "Excuses AP Dhillon",
    "yt": "vX2cDW8LUWk"
  },
  {
    "title": "Pasoori",
    "artist": "Ali Sethi, Shae Gill",
    "year": 2022,
    "q": "Pasoori Ali Sethi, Shae Gill",
    "yt": "5Eqb_-j3FDA"
  },
  {
    "title": "Lehenga",
    "artist": "Jass Manak",
    "year": 2019,
    "q": "Lehenga Jass Manak",
    "yt": "RKioDWlajvo"
  }
];

window.SITE = {
  "name": "Punjabi",
  "tagline": "Sarson fields, a dhol that won't quit, swag inherited not bought.",
  "glyph": "✺",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLtzd6aavJNLgGx3tivZKYKHZQpfdi3Lw4",
  "maxSeconds": null
};
