/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Aashiq Banaya Aapne",
    "artist": "Himesh Reshammiya, Shreya Ghoshal",
    "year": 2005,
    "q": "Aashiq Banaya Aapne Himesh Reshammiya, Shreya Ghoshal",
    "yt": "al1Rlto5o6E"
  },
  {
    "title": "Jhalak Dikhla Ja",
    "artist": "Himesh Reshammiya",
    "year": 2006,
    "q": "Jhalak Dikhla Ja Himesh Reshammiya",
    "yt": "vnlk8V-q0oU"
  },
  {
    "title": "Tera Surroor",
    "artist": "Himesh Reshammiya",
    "year": 2006,
    "q": "Tera Surroor Himesh Reshammiya",
    "yt": "Oqe_2fs5RIQ"
  },
  {
    "title": "Afsana",
    "artist": "Himesh Reshammiya",
    "year": 2006,
    "q": "Afsana Himesh Reshammiya",
    "yt": "psaBpso9BG4"
  },
  {
    "title": "Naam Hai Tera",
    "artist": "Himesh Reshammiya",
    "year": 2006,
    "q": "Naam Hai Tera Himesh Reshammiya",
    "yt": "DULrvDVqyXI"
  },
  {
    "title": "Tum Saanson Mein",
    "artist": "Himesh Reshammiya, Tulsi Kumar",
    "year": 2007,
    "q": "Tum Saanson Mein Himesh Reshammiya, Tulsi Kumar",
    "yt": "x9RSKCfUnhg"
  },
  {
    "title": "Soniye",
    "artist": "Himesh Reshammiya",
    "year": 2006,
    "q": "Soniye Himesh Reshammiya",
    "yt": "RE46-BjrhNQ"
  },
  {
    "title": "Main Jahan Rahoon",
    "artist": "Himesh Reshammiya",
    "year": 2007,
    "q": "Main Jahan Rahoon Himesh Reshammiya",
    "yt": "ZQlH0D_GPiE"
  },
  {
    "title": "Teri Meri",
    "artist": "Himesh Reshammiya, Shreya Ghoshal",
    "year": 2011,
    "q": "Teri Meri Himesh Reshammiya, Shreya Ghoshal",
    "yt": "VCTk-IUNnpc"
  },
  {
    "title": "Hookah Bar",
    "artist": "Himesh Reshammiya, Vineet Singh, Aman Trikha",
    "year": 2012,
    "q": "Hookah Bar Himesh Reshammiya, Vineet Singh, Aman Trikha",
    "yt": "EvMKzUCifiU"
  },
  {
    "title": "Long Drive",
    "artist": "Himesh Reshammiya",
    "year": 2012,
    "q": "Long Drive Himesh Reshammiya",
    "yt": "TCOlBJOo5Zw"
  },
  {
    "title": "Balma",
    "artist": "Himesh Reshammiya, Shreya Ghoshal",
    "year": 2012,
    "q": "Balma Himesh Reshammiya, Shreya Ghoshal",
    "yt": "kPmAJPUVY8I"
  },
  {
    "title": "Chalao Na Naino Se",
    "artist": "Himesh Reshammiya, Shreya Ghoshal",
    "year": 2012,
    "q": "Chalao Na Naino Se Himesh Reshammiya, Shreya Ghoshal",
    "yt": "z-2ObrQ2Ct0"
  },
  {
    "title": "Jumme Ki Raat",
    "artist": "Himesh Reshammiya, Palak Muchhal",
    "year": 2014,
    "q": "Jumme Ki Raat Himesh Reshammiya, Palak Muchhal",
    "yt": "y8w8-T7AoSo"
  },
  {
    "title": "Tu Hi Tu",
    "artist": "Himesh Reshammiya",
    "year": 2014,
    "q": "Tu Hi Tu Himesh Reshammiya",
    "yt": "DULrvDVqyXI"
  },
  {
    "title": "Ice Cream Khaungi",
    "artist": "Himesh Reshammiya, Palak Muchhal",
    "year": 2014,
    "q": "Ice Cream Khaungi Himesh Reshammiya, Palak Muchhal",
    "yt": "bsBQFYQCH-o"
  },
  {
    "title": "Hangover",
    "artist": "Himesh Reshammiya, Shreya Ghoshal",
    "year": 2014,
    "q": "Hangover Himesh Reshammiya, Shreya Ghoshal",
    "yt": "1gqBb4Y7LJA"
  },
  {
    "title": "Dard Dilo Ke",
    "artist": "Himesh Reshammiya",
    "year": 2014,
    "q": "Dard Dilo Ke Himesh Reshammiya",
    "yt": "CExS4CBufng"
  }
];

window.SITE = {
  "name": "Himesh Reshammiya",
  "tagline": "One cap, one nasal high note, a thousand ringtone hits.",
  "glyph": "♫",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLEOiStG7CxDKEx0W4AMsDlEDk2qrlns0I",
  "maxSeconds": null
};
