/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Phir Mohabbat",
    "artist": "Arijit Singh, Mithoon",
    "year": 2011,
    "q": "Phir Mohabbat Arijit Singh, Mithoon",
    "yt": "m1rcse8INWk"
  },
  {
    "title": "Duaa",
    "artist": "Arijit Singh, Nandini Srikar",
    "year": 2012,
    "q": "Duaa Arijit Singh, Nandini Srikar",
    "yt": "j3BiIJKBlYE"
  },
  {
    "title": "Raabta",
    "artist": "Arijit Singh, Hamsika Iyer",
    "year": 2012,
    "q": "Raabta Arijit Singh, Hamsika Iyer",
    "yt": "piUHBTXsoiY"
  },
  {
    "title": "Tum Hi Ho",
    "artist": "Arijit Singh",
    "year": 2013,
    "q": "Tum Hi Ho Arijit Singh",
    "yt": "fsiPzT50ZiM"
  },
  {
    "title": "Chahun Main Ya Naa",
    "artist": "Arijit Singh, Palak Muchhal",
    "year": 2013,
    "q": "Chahun Main Ya Naa Arijit Singh, Palak Muchhal",
    "yt": "Q4F7MF5Vzt0"
  },
  {
    "title": "Ilahi",
    "artist": "Arijit Singh",
    "year": 2013,
    "q": "Ilahi Arijit Singh",
    "yt": "fdubeMFwuGs"
  },
  {
    "title": "Muskurane",
    "artist": "Arijit Singh",
    "year": 2014,
    "q": "Muskurane Arijit Singh",
    "yt": "2ltGXfmI6mk"
  },
  {
    "title": "Samjhawan",
    "artist": "Arijit Singh, Shreya Ghoshal",
    "year": 2014,
    "q": "Samjhawan Arijit Singh, Shreya Ghoshal",
    "yt": "yQ6d627OZig"
  },
  {
    "title": "Manwa Laage",
    "artist": "Arijit Singh, Shreya Ghoshal",
    "year": 2014,
    "q": "Manwa Laage Arijit Singh, Shreya Ghoshal",
    "yt": "d8IT-16kA8M"
  },
  {
    "title": "Sooraj Dooba Hain",
    "artist": "Arijit Singh, Aditi Singh Sharma",
    "year": 2015,
    "q": "Sooraj Dooba Hain Arijit Singh, Aditi Singh Sharma",
    "yt": "nJZcbidTutE"
  },
  {
    "title": "Gerua",
    "artist": "Arijit Singh, Antara Mitra",
    "year": 2015,
    "q": "Gerua Arijit Singh, Antara Mitra",
    "yt": "AEIVhBS6baE"
  },
  {
    "title": "Janam Janam",
    "artist": "Arijit Singh, Antara Mitra",
    "year": 2015,
    "q": "Janam Janam Arijit Singh, Antara Mitra",
    "yt": "g44iifQIFyM"
  },
  {
    "title": "Ae Dil Hai Mushkil",
    "artist": "Arijit Singh",
    "year": 2016,
    "q": "Ae Dil Hai Mushkil Arijit Singh",
    "yt": "wx89ZdkwtS8"
  },
  {
    "title": "Channa Mereya",
    "artist": "Arijit Singh",
    "year": 2016,
    "q": "Channa Mereya Arijit Singh",
    "yt": "FO9rBogdRRQ"
  },
  {
    "title": "Enna Sona",
    "artist": "Arijit Singh, Shreya Ghoshal",
    "year": 2017,
    "q": "Enna Sona Arijit Singh, Shreya Ghoshal",
    "yt": "mrdRHsIkK_c"
  },
  {
    "title": "Zaalima",
    "artist": "Arijit Singh, Harshdeep Kaur",
    "year": 2017,
    "q": "Zaalima Arijit Singh, Harshdeep Kaur",
    "yt": "eXkHvT--DBU"
  },
  {
    "title": "Hawayein",
    "artist": "Arijit Singh",
    "year": 2017,
    "q": "Hawayein Arijit Singh",
    "yt": "cYOB941gyXI"
  },
  {
    "title": "Tera Yaar Hoon Main",
    "artist": "Arijit Singh",
    "year": 2018,
    "q": "Tera Yaar Hoon Main Arijit Singh",
    "yt": "EatzcaVJRMs"
  },
  {
    "title": "Khairiyat",
    "artist": "Arijit Singh",
    "year": 2019,
    "q": "Khairiyat Arijit Singh",
    "yt": "qTAegUy7mo4"
  },
  {
    "title": "Kesariya",
    "artist": "Arijit Singh",
    "year": 2022,
    "q": "Kesariya Arijit Singh",
    "yt": "6mr4cYJ7yew"
  }
];

window.SITE = {
  "name": "Arijit Singh",
  "tagline": "One unread chat, city rain, and a voice that reads it out loud.",
  "glyph": "☂",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLizEqzsgQvPp8kTHGV9o6bjkz6t0TJtjm",
  "maxSeconds": null
};
