/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Tujhe Dekha To",
    "artist": "Kumar Sanu, Lata Mangeshkar",
    "year": 1995,
    "q": "Tujhe Dekha To Kumar Sanu, Lata Mangeshkar",
    "yt": null
  },
  {
    "title": "Pehla Nasha",
    "artist": "Udit Narayan, Sadhana Sargam",
    "year": 1992,
    "q": "Pehla Nasha Udit Narayan, Sadhana Sargam",
    "yt": null
  },
  {
    "title": "Tum Paas Aaye",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1998,
    "q": "Tum Paas Aaye Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Kuch Kuch Hota Hai",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1998,
    "q": "Kuch Kuch Hota Hai Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Suraj Hua Maddham",
    "artist": "Sonu Nigam, Alka Yagnik",
    "year": 2001,
    "q": "Suraj Hua Maddham Sonu Nigam, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Tere Liye",
    "artist": "Lata Mangeshkar, Roop Kumar Rathod",
    "year": 2004,
    "q": "Tere Liye Lata Mangeshkar, Roop Kumar Rathod",
    "yt": null
  },
  {
    "title": "Bahon Ke Darmiyan",
    "artist": "Kumar Sanu, Kavita Krishnamurthy",
    "year": 1996,
    "q": "Bahon Ke Darmiyan Kumar Sanu, Kavita Krishnamurthy",
    "yt": null
  },
  {
    "title": "Aankhon Ki Gustakhiyan",
    "artist": "Kumar Sanu, Kavita Krishnamurthy",
    "year": 1999,
    "q": "Aankhon Ki Gustakhiyan Kumar Sanu, Kavita Krishnamurthy",
    "yt": null
  },
  {
    "title": "Tadap Tadap",
    "artist": "K. K.",
    "year": 1999,
    "q": "Tadap Tadap K. K.",
    "yt": null
  },
  {
    "title": "Chand Chhupa Badal Mein",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1999,
    "q": "Chand Chhupa Badal Mein Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Zara Sa Jhoom Loon Main",
    "artist": "Abhijeet, Asha Bhosle",
    "year": 1995,
    "q": "Zara Sa Jhoom Loon Main Abhijeet, Asha Bhosle",
    "yt": null
  },
  {
    "title": "Ho Gaya Hai Tujhko",
    "artist": "Udit Narayan, Lata Mangeshkar",
    "year": 1995,
    "q": "Ho Gaya Hai Tujhko Udit Narayan, Lata Mangeshkar",
    "yt": null
  },
  {
    "title": "Dil To Pagal Hai",
    "artist": "Lata Mangeshkar, Udit Narayan",
    "year": 1997,
    "q": "Dil To Pagal Hai Lata Mangeshkar, Udit Narayan",
    "yt": null
  },
  {
    "title": "Are Re Are",
    "artist": "Udit Narayan, Lata Mangeshkar",
    "year": 1997,
    "q": "Are Re Are Udit Narayan, Lata Mangeshkar",
    "yt": null
  },
  {
    "title": "Koi Mil Gaya",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1998,
    "q": "Koi Mil Gaya Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Sandese Aate Hain",
    "artist": "Sonu Nigam, Roop Kumar Rathod",
    "year": 1997,
    "q": "Sandese Aate Hain Sonu Nigam, Roop Kumar Rathod",
    "yt": null
  },
  {
    "title": "Pyar Hua Chupke Se",
    "artist": "Kavita Krishnamurthy",
    "year": 1994,
    "q": "Pyar Hua Chupke Se Kavita Krishnamurthy",
    "yt": null
  },
  {
    "title": "Ae Ajnabi",
    "artist": "Udit Narayan, Mahalaxmi Iyer",
    "year": 1998,
    "q": "Ae Ajnabi Udit Narayan, Mahalaxmi Iyer",
    "yt": null
  }
];

window.SITE = {
  "name": "VHS",
  "tagline": "Slow-motion garland exchange, date stamp burned into the corner.",
  "glyph": "▣",
  "shuffle": true,
  "searchFallback": true
};
