/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Lollipop Lagelu",
    "artist": "Dinesh Lal Yadav (Nirahua)",
    "year": 2008,
    "q": "Lollipop Lagelu Dinesh Lal Yadav (Nirahua)",
    "yt": null
  },
  {
    "title": "Chhalakata Hamro Jawaniya",
    "artist": "Pawan Singh",
    "year": 2017,
    "q": "Chhalakata Hamro Jawaniya Pawan Singh",
    "yt": "c4JD7rEtIj8"
  },
  {
    "title": "Hello Kaun",
    "artist": "Pawan Singh",
    "year": 2018,
    "q": "Hello Kaun Pawan Singh",
    "yt": null
  },
  {
    "title": "Balam Ji Love You",
    "artist": "Pawan Singh",
    "year": 2018,
    "q": "Balam Ji Love You Pawan Singh",
    "yt": null
  },
  {
    "title": "Kala Odhani",
    "artist": "Pawan Singh, Shilpi Raj",
    "year": 2024,
    "q": "Kala Odhani Pawan Singh, Shilpi Raj",
    "yt": "mOu_zBiFi5U"
  },
  {
    "title": "Lal Ghaghra",
    "artist": "Pawan Singh, Shilpi Raj",
    "year": 2024,
    "q": "Lal Ghaghra Pawan Singh, Shilpi Raj",
    "yt": "qZId59qml_4"
  },
  {
    "title": "Rajaji Ke Dilwa",
    "artist": "Pawan Singh, Shivani Singh",
    "year": 2024,
    "q": "Rajaji Ke Dilwa Pawan Singh, Shivani Singh",
    "yt": "mmpibVMv0AA"
  },
  {
    "title": "Jila Top",
    "artist": "Khesari Lal Yadav",
    "year": 2019,
    "q": "Jila Top Khesari Lal Yadav",
    "yt": null
  },
  {
    "title": "Palang Sagwan Ke",
    "artist": "Khesari Lal Yadav",
    "year": 2021,
    "q": "Palang Sagwan Ke Khesari Lal Yadav",
    "yt": "BdMTcZwCokI"
  },
  {
    "title": "Nathuniya",
    "artist": "Khesari Lal Yadav, Priyanka Singh",
    "year": 2023,
    "q": "Nathuniya Khesari Lal Yadav, Priyanka Singh",
    "yt": "iYRqAc10Ii8"
  },
  {
    "title": "Lehenga Lucknowwa",
    "artist": "Khesari Lal Yadav",
    "year": 2023,
    "q": "Lehenga Lucknowwa Khesari Lal Yadav",
    "yt": null
  },
  {
    "title": "Payal",
    "artist": "Khesari Lal Yadav, Shilpi Raj",
    "year": 2024,
    "q": "Payal Khesari Lal Yadav, Shilpi Raj",
    "yt": null
  },
  {
    "title": "Pagli Dekhave Agarbatti",
    "artist": "Neelkamal Singh",
    "year": 2024,
    "q": "Pagli Dekhave Agarbatti Neelkamal Singh",
    "yt": "YAtgKpugpQ4"
  },
  {
    "title": "Maja Milela Na Pura",
    "artist": "Neelkamal Singh",
    "year": 2024,
    "q": "Maja Milela Na Pura Neelkamal Singh",
    "yt": "oxhdCm1ZGX8"
  },
  {
    "title": "Saiyan Ji Dilwa Mangele Gamcha Bichai Ke",
    "artist": "Neelkamal Singh",
    "year": 2022,
    "q": "Saiyan Ji Dilwa Mangele Gamcha Bichai Ke Neelkamal Singh",
    "yt": "5IjA5rfllC0"
  },
  {
    "title": "Chulhi Me Jhok Di",
    "artist": "Shilpi Raj",
    "year": 2024,
    "q": "Chulhi Me Jhok Di Shilpi Raj",
    "yt": "uUzSniB8tLk"
  },
  {
    "title": "Nadi Biche Naiya Dole",
    "artist": "Shilpi Raj, Rani",
    "year": 2024,
    "q": "Nadi Biche Naiya Dole Shilpi Raj, Rani",
    "yt": "BRQ-n5OYUuM"
  },
  {
    "title": "Saiyaan Ji Sarkave",
    "artist": "Shilpi Raj",
    "year": 2022,
    "q": "Saiyaan Ji Sarkave Shilpi Raj",
    "yt": null
  }
];

window.SITE = {
  "name": "Bhojpuri",
  "tagline": "Sequin disco, loud speakers, and songs your landlord also knows.",
  "glyph": "★",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLGqUOt0CNckJib_vLMdgWzmIRd2X7dG5Z",
  "maxSeconds": null
};
