/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Lollipop Lagelu",
    "artist": "Dinesh Lal Yadav (Nirahua)",
    "year": 2008,
    "q": "Lollipop Lagelu Dinesh Lal Yadav (Nirahua)",
    "yt": null
  },
  {
    "title": "Chhalakata Hamro Jawaniya",
    "artist": "Pawan Singh",
    "year": 2017,
    "q": "Chhalakata Hamro Jawaniya Pawan Singh",
    "yt": "c4JD7rEtIj8"
  },
  {
    "title": "Kamariya Hila Rahi Hai",
    "artist": "Ritesh Pandey",
    "year": 2019,
    "q": "Kamariya Hila Rahi Hai Ritesh Pandey",
    "yt": null
  },
  {
    "title": "Hello Kaun",
    "artist": "Pawan Singh",
    "year": 2018,
    "q": "Hello Kaun Pawan Singh",
    "yt": null
  },
  {
    "title": "Jila Top",
    "artist": "Khesari Lal Yadav",
    "year": 2019,
    "q": "Jila Top Khesari Lal Yadav",
    "yt": null
  },
  {
    "title": "Balam Ji Love You",
    "artist": "Pawan Singh",
    "year": 2018,
    "q": "Balam Ji Love You Pawan Singh",
    "yt": null
  },
  {
    "title": "Saiyan Arab Gail Na",
    "artist": "Kalpana",
    "year": 1990,
    "q": "Saiyan Arab Gail Na Kalpana",
    "yt": null
  },
  {
    "title": "Saiyaan Ji Sarkave",
    "artist": "Shilpi Raj",
    "year": 2022,
    "q": "Saiyaan Ji Sarkave Shilpi Raj",
    "yt": null
  }
];

window.SITE = {
  "name": "Bhojpuri",
  "tagline": "Sequin disco, loud speakers, and songs your landlord also knows.",
  "glyph": "★",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLGqUOt0CNckJib_vLMdgWzmIRd2X7dG5Z",
  "maxSeconds": null
};
