/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Hotel California",
    "artist": "Eagles",
    "year": 1976,
    "q": "Hotel California Eagles",
    "yt": "09839DpTctU"
  },
  {
    "title": "Stairway to Heaven",
    "artist": "Led Zeppelin",
    "year": 1971,
    "q": "Stairway to Heaven Led Zeppelin",
    "yt": "QkF3oxziUI4"
  },
  {
    "title": "Whole Lotta Love",
    "artist": "Led Zeppelin",
    "year": 1969,
    "q": "Whole Lotta Love Led Zeppelin",
    "yt": "HQmmM_qwG4k"
  },
  {
    "title": "Comfortably Numb",
    "artist": "Pink Floyd",
    "year": 1979,
    "q": "Comfortably Numb Pink Floyd",
    "yt": "_FrOQC-zEog"
  },
  {
    "title": "Wish You Were Here",
    "artist": "Pink Floyd",
    "year": 1975,
    "q": "Wish You Were Here Pink Floyd",
    "yt": "hjpF8ukSrvk"
  },
  {
    "title": "Bohemian Rhapsody",
    "artist": "Queen",
    "year": 1975,
    "q": "Bohemian Rhapsody Queen",
    "yt": "fJ9rUzIMcZQ"
  },
  {
    "title": "Sweet Child O' Mine",
    "artist": "Guns N' Roses",
    "year": 1987,
    "q": "Sweet Child O' Mine Guns N' Roses",
    "yt": "1w7OgIMMRc4"
  },
  {
    "title": "Smoke on the Water",
    "artist": "Deep Purple",
    "year": 1972,
    "q": "Smoke on the Water Deep Purple",
    "yt": "Q2FzZSBD5LE"
  },
  {
    "title": "Highway to Hell",
    "artist": "AC/DC",
    "year": 1979,
    "q": "Highway to Hell AC/DC",
    "yt": "l482T0yNkeo"
  },
  {
    "title": "Back in Black",
    "artist": "AC/DC",
    "year": 1980,
    "q": "Back in Black AC/DC",
    "yt": "pAgnJDJN4VA"
  },
  {
    "title": "Paint It, Black",
    "artist": "The Rolling Stones",
    "year": 1966,
    "q": "Paint It, Black The Rolling Stones",
    "yt": "170sceOWWXc"
  },
  {
    "title": "Layla",
    "artist": "Derek and the Dominos",
    "year": 1970,
    "q": "Layla Derek and the Dominos",
    "yt": "TngViNw2pOo"
  },
  {
    "title": "Born to Be Wild",
    "artist": "Steppenwolf",
    "year": 1968,
    "q": "Born to Be Wild Steppenwolf",
    "yt": "igvP806798U"
  },
  {
    "title": "More Than a Feeling",
    "artist": "Boston",
    "year": 1976,
    "q": "More Than a Feeling Boston",
    "yt": "oR4uKcvQbGQ"
  },
  {
    "title": "Dream On",
    "artist": "Aerosmith",
    "year": 1973,
    "q": "Dream On Aerosmith",
    "yt": "sZfZ8uWaOFI"
  },
  {
    "title": "Free Bird",
    "artist": "Lynyrd Skynyrd",
    "year": 1973,
    "q": "Free Bird Lynyrd Skynyrd",
    "yt": "MQNRKX8GwPo"
  },
  {
    "title": "Fortunate Son",
    "artist": "Creedence Clearwater Revival",
    "year": 1969,
    "q": "Fortunate Son Creedence Clearwater Revival",
    "yt": "ec0XKhAHR5I"
  },
  {
    "title": "Barracuda",
    "artist": "Heart",
    "year": 1977,
    "q": "Barracuda Heart",
    "yt": "VdOkQ6THDVw"
  },
  {
    "title": "Rock You Like a Hurricane",
    "artist": "Scorpions",
    "year": 1984,
    "q": "Rock You Like a Hurricane Scorpions",
    "yt": "6yP1tcy9a10"
  },
  {
    "title": "Summer of '69",
    "artist": "Bryan Adams",
    "year": 1984,
    "q": "Summer of '69 Bryan Adams",
    "yt": "9f06QZCVUHg"
  }
];

window.SITE = {
  "name": "Valve",
  "tagline": "One amp, warm glass tubes, and the riffs your father still air-guitars.",
  "glyph": "⚡",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PL9xheEG-eSrSzt05VVCLfNRBjnNmRZtbx",
  "maxSeconds": null
};
