/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Kelwa Ke Paat Par",
    "artist": "Sharda Sinha",
    "year": null,
    "q": "Kelwa Ke Paat Par Sharda Sinha",
    "yt": "knZ8b5YnQiY"
  },
  {
    "title": "Pahile Pahil",
    "artist": "Sharda Sinha",
    "year": null,
    "q": "Pahile Pahil Sharda Sinha",
    "yt": "6nPhZkZF4kk"
  },
  {
    "title": "Bahangi Laga Ke",
    "artist": "Sharda Sinha",
    "year": null,
    "q": "Bahangi Laga Ke Sharda Sinha",
    "yt": "MEnyozGodAU"
  },
  {
    "title": "Supawo Naa Mile Maahi",
    "artist": "Sharda Sinha",
    "year": null,
    "q": "Supawo Naa Mile Maahi Sharda Sinha",
    "yt": "BC5I-33GNDA"
  },
  {
    "title": "Uga Hai Suraj Dev",
    "artist": "Anuradha Paudwal",
    "year": null,
    "q": "Uga Hai Suraj Dev Anuradha Paudwal",
    "yt": "6e6Hp6R5SVU"
  },
  {
    "title": "Hey Chhathi Maiya",
    "artist": "Narendra Chanchal",
    "year": null,
    "q": "Hey Chhathi Maiya Narendra Chanchal",
    "yt": "fHk5SieXZtw"
  },
  {
    "title": "Saat Samundar Paar",
    "artist": "Pawan Singh",
    "year": null,
    "q": "Saat Samundar Paar Pawan Singh",
    "yt": "84B0-P9qcNs"
  },
  {
    "title": "Jai Chhathi Maiya",
    "artist": "Kalpana Patowary",
    "year": null,
    "q": "Jai Chhathi Maiya Kalpana Patowary",
    "yt": "GRC19OaLLUo"
  }
];

window.SITE = {
  "name": "Chhath",
  "tagline": "Waist-deep in the river, offering the last light to the sun.",
  "glyph": "☀",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLyXHXSHxLqKy7hxvVopat1bvXLiyZS4Ga",
  "maxSeconds": null
};
