/* generated by build.mjs — safe to hand-edit the "yt" ids,
   they are preserved on the next build. */
window.PLAYLIST = [
  {
    "title": "Papa Kehte Hain",
    "artist": "Udit Narayan",
    "year": 1988,
    "q": "Papa Kehte Hain Udit Narayan",
    "yt": "ngBEVUKnhgY"
  },
  {
    "title": "Ae Mere Humsafar",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1988,
    "q": "Ae Mere Humsafar Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Pehla Nasha",
    "artist": "Udit Narayan, Sadhana Sargam",
    "year": 1992,
    "q": "Pehla Nasha Udit Narayan, Sadhana Sargam",
    "yt": null
  },
  {
    "title": "Dhak Dhak Karne Laga",
    "artist": "Anuradha Paudwal, Udit Narayan",
    "year": 1992,
    "q": "Dhak Dhak Karne Laga Anuradha Paudwal, Udit Narayan",
    "yt": null
  },
  {
    "title": "Jaadu Teri Nazar",
    "artist": "Udit Narayan",
    "year": 1993,
    "q": "Jaadu Teri Nazar Udit Narayan",
    "yt": null
  },
  {
    "title": "Tu Cheez Badi Hai Mast",
    "artist": "Udit Narayan, Kavita Krishnamurthy",
    "year": 1994,
    "q": "Tu Cheez Badi Hai Mast Udit Narayan, Kavita Krishnamurthy",
    "yt": null
  },
  {
    "title": "Ho Gaya Hai Tujhko To Pyar Hai",
    "artist": "Udit Narayan, Lata Mangeshkar",
    "year": 1995,
    "q": "Ho Gaya Hai Tujhko To Pyar Hai Udit Narayan, Lata Mangeshkar",
    "yt": null
  },
  {
    "title": "Mehndi Laga Ke Rakhna",
    "artist": "Udit Narayan, Lata Mangeshkar",
    "year": 1995,
    "q": "Mehndi Laga Ke Rakhna Udit Narayan, Lata Mangeshkar",
    "yt": null
  },
  {
    "title": "Ruk Ja O Dil Deewane",
    "artist": "Udit Narayan",
    "year": 1995,
    "q": "Ruk Ja O Dil Deewane Udit Narayan",
    "yt": null
  },
  {
    "title": "Pardesi Pardesi",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1996,
    "q": "Pardesi Pardesi Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Kuch Kuch Hota Hai",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1998,
    "q": "Kuch Kuch Hota Hai Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Ladki Badi Anjani Hai",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1998,
    "q": "Ladki Badi Anjani Hai Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Chand Chhupa Badal Mein",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 1999,
    "q": "Chand Chhupa Badal Mein Udit Narayan, Alka Yagnik",
    "yt": "lqYUYuw0b1k"
  },
  {
    "title": "Kaho Naa Pyaar Hai",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 2000,
    "q": "Kaho Naa Pyaar Hai Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Main Nikla Gaddi Leke",
    "artist": "Udit Narayan",
    "year": 2001,
    "q": "Main Nikla Gaddi Leke Udit Narayan",
    "yt": null
  },
  {
    "title": "Udja Kale Kawan",
    "artist": "Udit Narayan",
    "year": 2001,
    "q": "Udja Kale Kawan Udit Narayan",
    "yt": null
  },
  {
    "title": "Idhar Chala Main Udhar Chala",
    "artist": "Udit Narayan, Alka Yagnik",
    "year": 2003,
    "q": "Idhar Chala Main Udhar Chala Udit Narayan, Alka Yagnik",
    "yt": null
  },
  {
    "title": "Main Yahaan Hoon",
    "artist": "Udit Narayan",
    "year": 2004,
    "q": "Main Yahaan Hoon Udit Narayan",
    "yt": "yqtGt2IjyKg"
  }
];

window.SITE = {
  "name": "Udit Narayan",
  "tagline": "First love, second-hand bicycle, one voice that never aged.",
  "glyph": "♥",
  "shuffle": true,
  "searchFallback": true,
  "ytPlaylist": "PLHNOeF1Yw3i0Swt9LUXe5azHLMDn7V-ng",
  "maxSeconds": null
};
